// Auto-generated by scripts/generate-config.js
window.APP_CONFIG = {
  API_BASE: "http://localhost:3000",
  SOCKET_URL: "http://localhost:5000",
  UPLOAD_URL: "http://localhost:5000/upload",
  SUPABASE_URL: "https://yvjjbtbvkhgefxyhisad.supabase.co",
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2ampidGJ2a2hnZWZ4eWhpc2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NTQ5NDcsImV4cCI6MjA5MDAzMDk0N30.ov5Tsj6EA9ygpwC-93FXafbgvwXGu9J3VajNfdQeT2M"
};
