const fs = require('fs');
const path = require('path');

const out = path.join(__dirname, '..', 'config.js');

// Use VERCEL_URL if available for automatic environment detection
const vercelUrl = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : null;
const API_BASE = process.env.API_BASE || vercelUrl || 'http://localhost:3000';
const SOCKET_URL = process.env.SOCKET_URL || 'http://localhost:5000';
const UPLOAD_URL = process.env.UPLOAD_URL || (SOCKET_URL + '/upload');

// new supabase keys (set these in Vercel env for production)
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_KEY = process.env.SUPABASE_KEY || '';

const content = `// Auto-generated by scripts/generate-config.js
window.APP_CONFIG = {
  API_BASE: ${JSON.stringify(API_BASE)},
  SOCKET_URL: ${JSON.stringify(SOCKET_URL)},
  UPLOAD_URL: ${JSON.stringify(UPLOAD_URL)},
  SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_KEY: ${JSON.stringify(SUPABASE_KEY)}
};
`;

fs.writeFileSync(out, content, 'utf8');
console.log('Written', out);